### ISSUE TITLE
Bug & Advise : ModuleNotFoundError: No module named 'porn.units'

### ISSUE THREAD

**Issue by 1lovejkovo** [xinghe98/91porn#4]
建议添加说明：先切换到项目目录下的porn/porn文件夹下再执行scrapy crawl Spider
不懂scrapy的话会一直报错哈哈哈

Bug截图：

![image](https://user-images.githubusercontent.com/87970169/173237987-6fd6743e-bf9c-4a68-92da-cb43166c51d6.png)

**Comment by hankssr** [comment]
我也出现的同样的问题,已经切换到文件夹下了还是不行

**Comment by xinghe98** [comment]
units.py 文件需要自己创建，里面包含代理ip地址和数据库连接地址，所以我没有传到GitHub上，后面会补充
